typography_spectrum: 0.7830298190309444
content_rating:
  adult: false
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.4980155318101728
  lightness: 0.7453467392577633
  saturation: 0.47176831471987735
  rhythmicContrast: 0.7994090815088711
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.23463005218957278
author:
  name: 'Sari Muda '
  url: www.awhotel.com
  email: smudawahab@gmail.com
name: AW Hotel & Convention Center
title: AW Hotel & Convention Center
